name: 'OnPublishECS'

on:  
  workflow_call:
    secrets:
      tfc-token:
        required: true

permissions:
  contents: read
  id-token: write

jobs:

  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4
      
    - name: "Terraform Apply"
      uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-apply@starter-actions
      with:
        tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
        tfc-token: "${{ secrets.tfc-token }}"
        tfc-workspace: "aws-ecs-starter-dev"
        tfc-cfg-directory: ""
        clusterName: ""
        serviceName: ""
        message: "Creating infrastructure in DEV environment"
