name: 'On Create Repository'

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
    
jobs:
  createWorkspace:
    runs-on: ubuntu-20.04    
    if: github.ref_name == 'main'
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4

      - id: tf-create-workspace-dev
        name: "[DEV] Create Workspace"
        uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-create-workspace@starter-actions
        with:
          workspaceName: "aws-ecs-starter-dev"
          organizationName: ${{ vars.TFC_ORGANIZATION }}
          token: ${{ secrets.TFC_TOKEN}}
          projectId: ${{ vars.DEV_SPACE_PRJ }}
      - id: tf-create-workspace-hml
        name: "[HML] Create Workspace"
        uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-create-workspace@main
        with:
          workspaceName: "aws-ecs-starter-hml"
          organizationName: ${{ vars.TFC_ORGANIZATION }}
          token: ${{ secrets.TFC_TOKEN}}
          projectId: ${{ vars.HML_SPACE_PRJ }}
      - id: tf-create-workspace-prd
        name: "[PRD] Create Workspace"
        uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-create-workspace@main
        with:
          workspaceName: "aws-ecs-starter-prd"
          organizationName: ${{ vars.TFC_ORGANIZATION }}
          token: ${{ secrets.TFC_TOKEN}}
          projectId: ${{ vars.PRD_SPACE_PRJ }}
