name: 'OnPullRequest'

on:  
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  starter-ecs-pull-request:
    uses: CailleachOrg/mudengine-ecs-starter/.github/workflows/starter-ecs-pull-request.yml@main
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}
