name: 'OnPushMain'

on:  
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  starter-ecs-dev-publish:
    uses: cailleach-devops/mudengine-ecs-starter/.github/workflows/aws-starter-ecs-publish.yml@main
    with:
      organization: "${{ vars.TFC_ORGANIZATION }}"
      environment: "dev"
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}
