name: 'OnPushMain'

on:  
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  starter-ecs-publish:
    environment: dev
    uses: cailleach-devops/mudengine-ecs-starter/.github/workflows/aws-starter-ecs-publish.yml@main
    with:
      tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
      environment: "dev"
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}

  starter-ecs-publish:
    environment: hml
    uses: cailleach-devops/mudengine-ecs-starter/.github/workflows/aws-starter-ecs-publish.yml@main
    with:
      tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
      environment: "hml"
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}      

  starter-ecs-publish:
    environment: prd
    uses: cailleach-devops/mudengine-ecs-starter/.github/workflows/aws-starter-ecs-publish.yml@main
    with:
      tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
      environment: "prd"
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}      